# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97c0217f3dbd5bcc5e28633ccbe9e46e8898ee738b50d8c90c6f556c6560088668259abf63533608d9afb50d8f68fc42e9a033821cc166c82c4ed85b6567b65

test:
  secret_key_base: 6b49240ccf02ef0f29dec4370c5aa79ad1cba54dc91124e69c72b0726fa0a952bab4b5f4089fb5e969e847a9ad8cdf0b0b69940bf3e603cb9b2f5bebf0c20c77
  active_merchant_login: 12345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
